### ISSUE TITLE
Add a link to the bug list view

### ISSUE THREAD

**Issue by lizzard** [emceeaich/bmo-comment-counts-app#1]
This looks useful! 

I'd love a handy link on this page to the bugzilla list view. Then I can check which versions are affected, whether the issue is fixed, and so on, with a glance over the list. I can do that with various extensions but a link would be nicer.

**Comment by emceeaich** [comment]
I've updated https://bmo-comment-counts-app.glitch.me/ with a link to the bug list. Thanks for the suggestion!
